Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ScoresWebsite.Models;

namespace ScoresWebsite.Controllers
{
    [Route("/Player")]
    public class PlayerController : Controller
    {
        DBContext dbConnect = new DBContext();
        public ActionResult Index()
        {
            Console.WriteLine("Hello Index");
            return View(dbConnect.Players.ToList());
        }

        //Unity Methods
        //Unity Form Acceptance
        [HttpPost]
        public ActionResult UnityRegister(string Username, string Email, string Password)
        {
            if (Username == null || Email == null || Password == null)
            {
                return null;
            }
            using (DBContext context = new DBContext())
            {
                context.Players.Add(new Player() { Username = Username, Email = Email, Password = Password });
                context.SaveChanges();
            }

            ViewBag.name = Username;
            return View();
        }

        [HttpPost]
        public ActionResult UnityLogin(string Username, string Password)
        {
            using (DBContext context = new DBContext())
            {
                var plyr = context.Players.Where(p => p.Username == Username && p.Password == Password).FirstOrDefault();
                if (plyr != null)
                {
                    Session["Username"] = plyr.Username.ToString();
                    return RedirectToAction("UnityLoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "Username or Password is incorrect");
                }
            }
            return View();
        }

        public ActionResult UnityLoggedIn()
        {
            if (Session["Username"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public ActionResult UnityUpdateScore(string Username, int ScoreIn)
        {
            using (DBContext context = new DBContext())
            {
                var plyr = context.Players.FirstOrDefault(p => p.Username == Username);
                    plyr.Score = ScoreIn;
                    context.SaveChanges();
            }
            return View();
        }
    }
}

Controllers/StripeController.cs
using Stripe;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScoresWebsite.Controllers
{
    public class StripeController : Controller
    {
        //Stripe.setPublishableKey('pk_test_qxv5VdJFxiLP3TNDpHNDDdMx');
        public ActionResult Index()
        {
            var stripePublishKey = ConfigurationManager.AppSettings["pk_test_qxv5VdJFxiLP3TNDpHNDDdMx"];
            ViewBag.StripePublishKey = stripePublishKey;
            return View();
        }

        public ActionResult Charge(string stripeEmail, string stripeToken)
        {
            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            var customer = customers.Create(new StripeCustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new StripeChargeCreateOptions
            {
                Amount = 100,//charge in cents
                Description = "Sample Charge",
                Currency = "eur",
                CustomerId = customer.Id
            });

            // further application specific code goes here

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Sharepoint Games", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" @Html.ActionLink("Leaderboards", "Index", "Player")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" @Html.ActionLink("Register", "WebRegister", "Home")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" @Html.ActionLink("Login", "WebLogin", "Home")</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" @Html.ActionLink("Payments", "Index", "Stripe")</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sharepoint Games 4th Year Computing Project (Andrew Conway X00121654)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>